CREATE OR REPLACE TRIGGER TRG_BANCO_DE_DADOS
AFTER INSERT ON BANCO_DE_DADOS 
FOR EACH ROW 

V_MEDIA_FINAL NUMBER;
V_APROVEITAMENTO NUMBER;

BEGIN
	SELECT 	BD.N1+((BD.AP + AL.AI)/ 2)/2 AS MEDIA_FINAL
	,		20 - FALTAS / 20 AS APROVEITAMENTO
	INTO V_MEDIA_FINAL, V_APROVEITAMENTO
	FROM BANCO_DE_DADOS BD, ALUNOS AL
	WHERE BD.COD_ALUNO = AL.MATRICULA
	
	UPDATE BANCO_DE_DADOS VALUES (MEDIA_FINAL, APROVEITAMENTO) 
	(V_MEDIA_FINAL, V_APROVEITAMENTO)
	WHERE ID = NEW.ID;
	
	COMMIT;
	
END;
END$$

DELIMITER ;

CREATE OR REPLACE TRIGGER TRG_CALCULO_DIF
AFTER INSERT ON CALCULO_DIF 
FOR EACH ROW 

V_MEDIA_FINAL NUMBER;
V_APROVEITAMENTO NUMBER;

BEGIN
	SELECT 	BD.N1+((BD.AP + AL.AI)/ 2)/2 AS MEDIA_FINAL
	,		20 - FALTAS / 20 AS APROVEITAMENTO
	INTO V_MEDIA_FINAL, V_APROVEITAMENTO
	FROM CALCULO_DIF BD, ALUNOS AL
	WHERE BD.COD_ALUNO = AL.MATRICULA
	
	UPDATE CALCULO_DIF VALUES (MEDIA_FINAL, APROVEITAMENTO) 
	(V_MEDIA_FINAL, V_APROVEITAMENTO)
	WHERE ID = NEW.ID;
	
	COMMIT;
	
END;
END$$

DELIMITER ;

CREATE OR REPLACE TRIGGER TRG_CALCULO_NUM
AFTER INSERT ON CALCULO_NUM 
FOR EACH ROW 

V_MEDIA_FINAL NUMBER;
V_APROVEITAMENTO NUMBER;

BEGIN
	SELECT 	BD.N1+((BD.AP + AL.AI)/ 2)/2 AS MEDIA_FINAL
	,		10 - FALTAS / 10 AS APROVEITAMENTO
	INTO V_MEDIA_FINAL, V_APROVEITAMENTO
	FROM CALCULO_NUM BD, ALUNOS AL
	WHERE BD.COD_ALUNO = AL.MATRICULA
	
	UPDATE CALCULO_NUM VALUES (MEDIA_FINAL, APROVEITAMENTO) 
	(V_MEDIA_FINAL, V_APROVEITAMENTO)
	WHERE ID = NEW.ID;
	
	COMMIT;
	
END;
END$$

DELIMITER ;

CREATE OR REPLACE TRIGGER TRG_SISTEMAS_OP
AFTER INSERT ON SISTEMAS_OP 
FOR EACH ROW 

V_MEDIA_FINAL NUMBER;
V_APROVEITAMENTO NUMBER;

BEGIN
	SELECT 	BD.N1+((BD.AP + AL.AI)/ 2)/2 AS MEDIA_FINAL
	,		20 - FALTAS / 20 AS APROVEITAMENTO
	INTO V_MEDIA_FINAL, V_APROVEITAMENTO
	FROM SISTEMAS_OP BD, ALUNOS AL
	WHERE BD.COD_ALUNO = AL.MATRICULA
	
	UPDATE SISTEMAS_OP VALUES (MEDIA_FINAL, APROVEITAMENTO) 
	(V_MEDIA_FINAL, V_APROVEITAMENTO)
	WHERE ID = NEW.ID;
	
	COMMIT;
	
END;
END$$

DELIMITER ;

CREATE OR REPLACE TRIGGER TRG_ARQUITETURA
AFTER INSERT ON ARQUITETURA 
FOR EACH ROW 

V_MEDIA_FINAL NUMBER;
V_APROVEITAMENTO NUMBER;

BEGIN
	SELECT 	BD.N1+((BD.AP + AL.AI)/ 2)/2 AS MEDIA_FINAL
	,		10 - FALTAS / 10 AS APROVEITAMENTO
	INTO V_MEDIA_FINAL, V_APROVEITAMENTO
	FROM ARQUITETURA BD, ALUNOS AL
	WHERE BD.COD_ALUNO = AL.MATRICULA
	
	UPDATE ARQUITETURA VALUES (MEDIA_FINAL, APROVEITAMENTO) 
	(V_MEDIA_FINAL, V_APROVEITAMENTO)
	WHERE ID = NEW.ID;
	
	COMMIT;
	
END;
END$$

DELIMITER ;

CREATE OR REPLACE TRIGGER TRG_ALGORITMOS
AFTER INSERT ON ALGORITMOS 
FOR EACH ROW 

V_MEDIA_FINAL NUMBER;
V_APROVEITAMENTO NUMBER;

BEGIN
	SELECT 	BD.N1+((BD.AP + AL.AI)/ 2)/2 AS MEDIA_FINAL
	,		20 - FALTAS / 20 AS APROVEITAMENTO
	INTO V_MEDIA_FINAL, V_APROVEITAMENTO
	FROM ALGORITMOS BD, ALUNOS AL
	WHERE BD.COD_ALUNO = AL.MATRICULA
	
	UPDATE ALGORITMOS VALUES (MEDIA_FINAL, APROVEITAMENTO) 
	(V_MEDIA_FINAL, V_APROVEITAMENTO)
	WHERE ID = NEW.ID;
	
	COMMIT;
	
END;
END$$