INSERT INTO ALUNOS(
	MATRICULA,NOME,IDADE,CPF,MATERIA_PREF,TRABALHA,INTEGRADA,MAIOR_NOTA,MENOR_NOTA)
VALUES(
	01,'VICENZO',19,'157.365.987-24','BANCO DE DADOS','S',6.5,8.5,3);

INSERT INTO BANCO_DE_DADOS(
	N1,AP,FALTAS)
VALUES( );

INSERT INTO CALCULO_DIF(
	N1,AP,FALTAS)
VALUES( );

INSERT INTO CALCULO_NUM(
	N1,AP,FALTAS)
VALUES( );

INSERT INTO SISTEMAS_OP(
	N1,AP,FALTAS)
VALUES( );

INSERT INTO ARQUITETURA(
	N1,AP,FALTAS)
VALUES( );

INSERT INTO ALGORITMOS(
	N1,AP,FALTAS)
VALUES( );